CREATE TABLE Books
(
 BookId INT IDENTITY PRIMARY KEY,
 Title NVARCHAR(50) NOT NULL,
 Price MONEY NOT NULL,
 PublishDate DATE NOT NULL,
 IsEBookAvailable BIT,
 Picture NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE TableOfContents
(
 Id INT IDENTITY PRIMARY KEY,
 ChapterNo NVARCHAR(50) NOT NULL,
 Topic NVARCHAR(50) NOT NULL,
 TotalPages INT NOT NULL,
 BookId INT NOT NULL REFERENCES Books(BookId)
)
GO
